Vagrant.configure("2") do |config|

  config.vm.define "tomcat" do |conf|
    conf.vm.hostname = "relateit-allinone"
    conf.vm.box = "centos65-x86_64-20131205"
    conf.vm.network "forwarded_port", guest: 8080, host: 28080
    conf.vm.network "forwarded_port", guest: 9200, host: 29200 
    conf.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.host_key_checking = false
      ansible.sudo = true
      ansible.sudo_user = 'root'
      ansible.groups = { "jdk" => ["tomcat"], "tomcat" => ["tomcat"], "relateit" => ["tomcat"], "elasticsearch" => ["tomcat"] } 
      ansible.verbose = 'vvvv'
    end
    conf.vm.provider "virtualbox" do |v|
      v.memory = 2048
    end
  end
end
